### PR TITLE
added GetCarrierForNumber and GetGeocodingForNumber

### PR DESCRIPTION
**Pull request by liuzl**

### CODE REVIEW

**Comment by nicpottier** [comment]
Hi @liuzl, thanks for the PR.

For consistency I think it would make more sense to have this data stored as protocol buffers instead of a string blob. Also either hooking in building this data into our main update command or creating a new wrapper around all of these commands would make sure these stay up to date when we do version rebuilds. (as I'm about to do)

With those two changes I'm up for merging this.

Thanks.

**Comment by liuzl** [comment]
Hi @nicpottier,
1. I have made the Carrier & Geocoding data in pb as defined in `prefixmap.proto`
2. The commands to build these two have been moved into `buildmetadata`

But, I still think that the idea of storing the Carrier & Geocoding data as string blobs is not that bad. As the source code files generated this way are smaller than the pb way(the built binaries are also smaller).
* `geocodings_txt.go` 2.8M vs. `prefix_to_geocodings.go` 5.3M
* `carriers_txt.go` 218K vs. `prefix_to_carriers.go` 193K 

And one more thing to mention: actually, at first, I was suppose to storing these data in the native Golang maps literally, and I tried. But it turned out that the source code files generated were big, and the built binaries are even bigger (more than 100M), also the building process took a very long time. So I switched to the string blob way at that time.

Thanks,
Zhanliang

**Comment by nicpottier** [comment]
Sorry for the delay on this, plan on merging this this week.

I don't mind the `.go` files being bigger and I would expect that since the byte representation isn't exactly small but you mention the binary is larger as well, do you have numbers for that by chance? There's SOME overhead for the PB format but it should be pretty small compared to the total size.

**Comment by nicpottier** [comment]
Closed in favor of https://github.com/nyaruka/phonenumbers/pull/10

**Pull request closed without merging**
