### PR TITLE
Update `GetLengthOfGeographicalAreaCode` to match recent libphonenumber changes

### PR DESCRIPTION
**Pull request by rowanseymour**
Addresses https://github.com/nyaruka/phonenumbers/issues/173

### CODE REVIEW

**Comment by alicebob** [comment]
Hi,

are you sure this is correct? Before this update +5214424123123 rendered as +524424123123 (the first "1" is gone). "+524424123123" also renders to that version (so it stays the same). The "521" prefix is an old one which is not in use anymore.

Random reference from the Interwebs:
> https://www.jaxcom.net/blog/important-changes-to-mexico-521-dialing-pattern/
> All calls to Mexico mobile phones:
>    Will no longer need the prefix of ‘521’ followed by the phone number.
>    Must strictly be dialed as ’52’ followed by the phone number.

**Comment by rowanseymour** [comment]
Hi @alicebob if you think there's a parsing problem please confirm the problem doesn't also exist in https://github.com/googlei18n/libphonenumber

**Comment by alicebob** [comment]
Even worse, that one rejects it with the 1:

https://libphonenumber.appspot.com/phonenumberparser?number=%2B524424123123
E164 format:	+524424123123

https://libphonenumber.appspot.com/phonenumberparser?number=%2B5214424123123
E164 format:	invalid

**Comment by rowanseymour** [comment]
Please report that then as an issue on that library as we are just a port of that and use their metadata

**Comment by alicebob** [comment]
On Tue, Jul 23, 2024 at 07:44:04AM -0700, Rowan Seymour wrote:
> Please report that then as an issue on that library as we are just a port of that and use their metadata

But nyaruka should also reject it, currently it doesn't.

**Comment by rowanseymour** [comment]
I agree but we are using their metadata, so it needs to be fixed there first

**Comment by alicebob** [comment]
thanks @rowanseymour . I made a separate issue, instead of talking in a closed PR.

**Pull request merged**
