### PR TITLE
Initial WIP support for emergency numbers and pay-numbers (ShortNumberInfo)

### PR DESCRIPTION
**Pull request by ecksun**
This PR is mainly as a starting point for discussion. Even though the code works and appears correct it is about the ugliest PR I have ever done :)

I would like to add support for what libphonenumber calls [ShortNumberInfo](https://javadoc.io/doc/com.googlecode.libphonenumber/libphonenumber/latest/com/google/i18n/phonenumbers/ShortNumberInfo.html).

More specifically I would like to add support for emergency numbers and expected costs.

I noticed that a lot of the infrastructure is the same between the two files, yet I'm not sure we can reuse the same data structures as the regions supported between them differ.

I put everything into its own package to get build errors for types I had missed and to make copy/pasting easier. It also matches the structure of libphonenumber.

I'm willing to do a lot of the work required here but I didn't want to start refactoring the entire library without first getting your thoughts on how to approach this.

### CODE REVIEW

**Comment by rowanseymour** [comment]
Closing in favor of https://github.com/nyaruka/phonenumbers/pull/113

**Comment by aarora-vonage** [comment]
Hello,
Thanks for creating this library. I jut wanna know why this PR was closed, After skimming through go codebase my understanding is that it doesn't have any API's for determining whether a number is emergency or not like we have in Google's libphonenumber(C++/Java) implementation.  Let me know in case I missed something.

**Comment by rowanseymour** [comment]
I think conflicts between the 2 PRs. We're definitely missing some short number functionality from Google's library. Would accept a PR that ports some of that functionality over.

**Comment by aarora-vonage** [comment]
@rowanseymour ,
Thanks for replying.
Since this library is meant to be exact replica in terms of functionality for Google's libphonenumber. Will you accept If I raise it as issue so that anyone can pick it up ??

**Comment by rowanseymour** [comment]
@aarora-vonage that's fine

**Pull request closed without merging**
