### PR TITLE
Bump dependencies to latest versions

### PR DESCRIPTION
**Pull request by alex**
This was done by doing:

```
$ go get -u github.com/golang/protobuf
$ go mod tidy
$ git commit
$ go get -u github.com/aws/aws-lambda-go
$ go mod tidy
$ git commit
```

### CODE REVIEW

**Comment by alex** [comment]
The new version of aws-lambda-go seems to require a more recent version of Go. I can either drop that commit, or make this library >=1.12. Do you have a preference?

**Comment by nicpottier** [comment]
Thanks for the PR. Would definitely prefer not to force go 1.12 if we can help it. Are these updates addressing any problems you've found?

**Comment by alex** [comment]
@nicpottier I was trying to clean up the numerous versions of `x/net` my project depends on. I'll drop the aws changes, which should let us support all the versions.

**Comment by nicpottier** [comment]
Thanks!

**Pull request merged**
