### PR TITLE
generate string values for ValidationResult

### PR DESCRIPTION
**Pull request by gregwebs**
I would like to be able to explain why a phone number is not valid as per #125 
This helps.

### CODE REVIEW

**Comment by rowanseymour** [comment]
I'm not sure I'm seeing the utility in having string versions of the error constants. If you want user facing errors it would be better to have a map of constants to strings. Unless the libphonenumber library offers similiar functionality I think I would lean toward not adding this.

**Comment by gregwebs** [comment]
I agree that for end users you would want to send the codes to the front-end and do localization, etc.

The intent of this is not for user-facing errors. It's for putting an error into our logs or otherwise being able to use them internally to quickly see why a phone number was rejected.

**Comment by gregwebs** [comment]
I can see the value in maintaining a strictly compatible API. It might be useful then to export a separate package (in this same repo though) that has functionality like this that is not present in the original library.

However, I think there is a way to get string representations automatically from the [original Java code](https://github.com/google/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/NumberParseException.java)?

**Comment by rowanseymour** [comment]
We're leaning to toward not adding the extra complexity here. Those constants don't change very often if ever so you can just map them to get something more descriptive for logs.

**Pull request closed without merging**
